### ISSUE TITLE
Can't open browser while `authorize`

### ISSUE THREAD

**Issue by corpix** [sferik/t#216]
`open_or_print` function doesn't print the actual URL of the page and can't open browser on my system(Arch Linux):

```
Press [Enter] to open the Twitter Developer site. 

...

Press [Enter] to open the Twitter app authorization page. 

Enter the supplied PIN:
```

As you can see, there is no URL in output. How could I help to resolve this problem(I don't know Ruby)?

**Comment by kleinfreund** [comment]
This issue is not reproducable for me.

Furthermore passing `--display-uri` actually leads to opening the URL in my browser where before it would just open a new blank browser window.

**Comment by corpix** [comment]
I am not using this tool now but if other people say this issue is resolved then closing it.
