### ISSUE TITLE
Bash, Can't end tweet with exclamation mark

### ISSUE THREAD

**Issue by richardj** [sferik/t#259]
When I compose a tweet and end it with an exclamation mark it will give an error:

```bash
bash: !": event not found
```
![t_exclamation_mark_bug](https://cloud.githubusercontent.com/assets/474024/5887258/9b9f75aa-a3c5-11e4-8fd8-b3763a107e58.jpg)

**Comment by sferik** [comment]
Sounds like a problem with your shell (`bash`), not with `t`? I don’t use bash but I assume there must be some way to escape the `!` character.

**Comment by mikemimik** [comment]
I have this issue as well. I'm using iTerm2 and the default bash shell. I can reproduce this error.

**Comment by richardj** [comment]
Since posting the issue i've moved to _zsh_ instead of _bash_ and the problem persists.

![screenshot 2016-06-20 11 09 49](https://cloud.githubusercontent.com/assets/474024/16188901/1c5a4a98-36d8-11e6-84d4-e427f58ecd08.png)

But escaping of the character is possible, you just have to know which characters you have to escape i suppose @mikemimik 

![screenshot 2016-06-20 11 11 54](https://cloud.githubusercontent.com/assets/474024/16188929/39bd03be-36d8-11e6-8a51-1917522156fc.png)

**Comment by Hund** [comment]
I might be a bit late to the party, but you can use strong quoting with single-quotes: 'text'.

**Comment by AJ-Acevedo** [comment]
I can confirm this issue still exists.
