### ISSUE TITLE
Feature request: conversation thread support

### ISSUE THREAD

**Issue by shedali** [sferik/t#265]
It would be great to be able to view twitter [conversations](https://blog.twitter.com/2013/keep-up-with-conversations-on-twitter).

This would provide a way to view context around a given tweet id.

**Comment by sferik** [comment]
I could implement a command like, `t thread TWEET_ID`, which would take the specified `TWEET_ID` and follow the `in_reply_to_status_id` up to the parent. Unfortunately, there’s no public API to go the other way (from parent to children). :frowning: /cc @jaakko-sf

**Comment by roylockhart** [comment]
would love that ! In addition I imagine something easy like : 

     t stream notifications
Which would display notification and if it is an answer, it would prompt 

    run 't reply status 583544300978179584` to answer.'

**Comment by haxpor** [comment]
@sferik and @roylockhart I did that going up to the upper stream. Check this PR out https://github.com/sferik/t/pull/274
