### ISSUE TITLE
warning: duplicated key at line 466 ignored: "inodot"

### ISSUE THREAD

**Issue by netllama** [sferik/t#294]
I just upgraded my OS (Fedora 22), which gave me ruby-2.2.3.  Now I'm seeing an error every time I run 't':
$ t timeline -r -l -n 55
/usr/local/share/gems/gems/htmlentities-4.3.1/lib/htmlentities/mappings/expanded.rb:465: warning: duplicated key at line 466 ignored: "inodot"

However, it also shows the expected immediately afterwards.

**Comment by sferik** [comment]
This is just a warning, so it should not interfere with anything.

You may want to try updating to the latest version of `htmlentities` with the command:

    gem update htmlentities

**Comment by netllama** [comment]
Updating htmlentities eliminated the warning.  thanks
