### ISSUE TITLE
Feature: `t view STATUS_ID` to open a tweet in a browser

### ISSUE THREAD

**Issue by patmaddox** [sferik/t#297]
After creating a status update, t conveniently prints the TWEET_ID.

I'd like to copy and paste the TWEET_ID into a new "t view" command to open the tweet in the browser.

*I'm posting this feature idea for early feedback, before implementing it myself*

**Comment by patmaddox** [comment]
Hey! Reading the help... helps :)

`t open -s 672225240378806272`

`-s, [--status], [--no-status]            # Specify input as a Twitter status ID instead of a screen name.`

**Comment by sferik** [comment]
Yup, you found it!

I recently got back from a long vacation, so I’m just getting a chance to go through the issues and pull requests you’ve opened now. Thanks for your patience.
