### ISSUE TITLE
Feature: `t reply STATUS_ID` opens a text editor / prompts for reply status

### ISSUE THREAD

**Issue by patmaddox** [sferik/t#298]
If I run `t update` with no status, a text editor opens where I can write my status.

If I run `t reply TWEET_ID` with no status, I get the error message:

```
ERROR: "t reply" was called with arguments ["672207489530597377"]
Usage: "t reply TWEET_ID MESSAGE"
```

I would like `reply` to behave the same as `update` in that it will prompt for the status by opening an editor.

*I'm posting this feature idea for early feedback, before implementing it myself*

**Comment by sferik** [comment]
:+1: to this idea. I’ll take a look at the implementation now.
