### ISSUE TITLE
How do I limit timeline or mentions to < 20?

### ISSUE THREAD

**Issue by RemoteCoderz** [sferik/t#305]
First of all I wanted to thank sferik for writing T. It's awesome. It has enabled me to start familiarizing myself with pi/raspbian before I dive in completely.

Onto my question:

When I trun t stream timeline or t mentions I'd love to be able to limit the amount of tweets I get back to say the last 3, 5, 10, up to your 20. 

I tried t timeline 10 for example and t mentions 10 but if vomitted errors messages at me and then I cowered under my desk for 5 minutes. 

Suggestions for this? 

THANK YOU!

**Comment by vishnuchilamakuru** [comment]
Now this support is added already. You can limit the number of tweets by using `-n 3` as mentioned below.
 Example:  `t timeline -n 3`
