### ISSUE TITLE
gem install t error messages

### ISSUE THREAD

**Issue by RemoteCoderz** [sferik/t#306]
So here's the message when I try to run it:

pi@raspberrypi:~ $ gem install t
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - /var/lib/gems

I've run a sudo apt-get update, and that ran fine, but then I tried a gem update --system and got this message:

pi@raspberrypi:~ $ gem update --system
Updating rubygems-update
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - /var/lib/gems

This is a clean install of raspbian on an 8gb microsd. 

Any thoughts?

**Comment by RemoteCoderz** [comment]
Sleep does a marvelous thing with solving problems....

"sudo gem install t"

¯\_(ツ)_/¯

**Comment by cognitive137** [comment]
This worked!
I use the MacOS and was unable to change the default permissions given, silly me, the solution was something was right there.
