### ISSUE TITLE
Timeline with tweet id?

### ISSUE THREAD

**Issue by okamos** [sferik/t#324]
Is it output or stream timeline with tweet id?

**Comment by Shwetakale** [comment]
@okamos Not sure I correctly understood your question. But are you asking whether it strams (make live API call and fetch) or just print data which is available?

It streams and shows it on console.

**Comment by okamos** [comment]
@Shwetakale Sorry, I forgot my question. :bow: Maybe I wanted this command. `t stream timeline @gem` Thank you for being patient with my English.
