### ISSUE TITLE
Feature request: --json

### ISSUE THREAD

**Issue by giacecco** [sferik/t#332]
... as --csv, but printing json.

**Comment by sferik** [comment]
Try [`twurl`](https://github.com/twitter/twurl).

**Comment by giacecco** [comment]
Thanks! However using the Twitter APIs and OAuth from code has become so easy now that one may write whatever he needs directly in Ruby or Nodejs etc. I keep love the idea of _t_ anyway, in the same way I love my news reader of choice _newsbeuter_. There's so much clutter in life, after all we just need to read the bl**dy text.
