### ISSUE TITLE
Piping with fortune isn't working

### ISSUE THREAD

**Issue by AugiteSoul** [sferik/t#374]
Doing 't update | fortune' isn't working. I get this error: Vim: Warning: Output is not a terminal , and the terminal stops responding.

**Comment by NicholBr** [comment]
can it be you really wanted to do 'fortune | t update', to tweet the output of 'fortune' ?

**Comment by AugiteSoul** [comment]
Nevermind, did a bash script to post the output of fortune to a tweet
