### ISSUE TITLE
dm command no longer works

### ISSUE THREAD

**Issue by mandeluna** [sferik/t#405]
The dm command gives the following error
```
/usr/local/bin/t: Sorry, that page does not exist.
```
I am pretty sure this is happening because Twitter changed the DM REST endpoints.

I'm not much of a ruby expert but I looked at the gemspec and it says that there is a dependency on 6.1.0 of the Twitter REST client. It does look up-to-date with the latest direct_messages events API.

In cli.rb there is a call to ```client.create_direct_message``` but I can't tell if it's calling the new API or the deprecated API.

I also know this is an old project and I'm not looking for someone to fix it for me, just suggestions on what I can do to fix it myself.  I've been poking through the code for a few hours and I'm not getting anywhere.

Thanks

**Comment by autodidacticon** [comment]
Looks like the path is wrong in the public `twitter` gem. It is correct in master. You can build the gem locally and install it and it appears to work.

**Comment by galenfarrel** [comment]
mandeluna, autodidacticon, did either of you  get the direct messaging working? Can you provide help in detail?

**Comment by mandeluna** [comment]
I haven't had time to look into this.

**Comment by autodidacticon** [comment]
@galenfarrel Pull down `git://github.com/sferik/twitter.git` and build / install master. That will temporarily resolve this issue until the gem is updated.

**Comment by galenfarrel** [comment]
@autodidacticon Thanks for your response. I'm new to ruby, and github. Will you explain what you mean by "Pull down" and "build / install"? I've already downloaded the t and installed it with the command "gem install twitter"...

**Comment by autodidacticon** [comment]
In a separate directory:
`git clone https://github.com/sferik/twitter.git`
and then 
`gem build twitter.gemspec`
`gem install twitter-6.2.0.gem`

**Comment by galenfarrel** [comment]
This caused the output to changed, but has not fixed the issue. And for clarity, the authorized account is a different account than the t dm @galen_farrel. Any ideas?

C:\Users\Galen\twitter-master>t dm @galen_farrel hi
C:/Ruby26-x64/bin/t: event.message_create.target.recipient_id: 'galen_farrel' is not a valid Long
Run `t authorize` to authorize.

And simliarly,
C:\Users\Galen>t dm @galen_farrel hi
C:/Ruby26-x64/bin/t: event.message_create.target.recipient_id: 'galen_farrel' is not a valid Long
Run `t authorize` to authorize.

**Comment by autodidacticon** [comment]
You need to invoke `dm` with the userId of the account. You can retrieve that with the `whoIs` command.

**Comment by galenfarrel** [comment]
@autodidacticon This is the ticket, it's working now. Thanks a heap for the help!

**Comment by onoakino** [comment]
I'm on t version 3.1.0 and I'm getting an error below when I try to send a DM. Note that I'm already authorized. I can post a twitter update fine, I can stream updates etc, but I can't successfuly send a Direct Message. Here's the command line output error:

`Miming-MacBook-Pro:~ miming$ t dm <userId of the account> hello
/Users/miming/.rbenv/versions/2.7.1/bin/t: Sorry, that page does not exist`

**Comment by jasalt** [comment]
Got it to work by upgrading twitter gem to 7.0.0, but that additionally needs a workaround for authentication to work (on mac) https://github.com/sferik/t/issues/402#issuecomment-643587697.
